### ISSUE TITLE
Switch to pyldap with 'bytes_mode=False' likely to break many Python2 consumers

### ISSUE THREAD

**Issue by bd808** [django-ldapdb/django-ldapdb#91] opened 2016-06-29 18:56 UTC
The changes in https://github.com/django-ldapdb/django-ldapdb/commit/46f474438b9529192c62eefb38e6a211964ae696 mean that all Python2 consumers must ensure that any and all string data passed to the library are unicode strings (`u'...'` or `unicode('...')`). Failure to do this conversion in the application prior to calling ldapdb will result in errors like: `All provided fields *must* be text when bytes mode is off; got 'cn'`.

This breaking change is probably worth documenting in the Changelog and README. Having read through https://github.com/pyldap/pyldap/issues/1 I think I understand why this change is being made, but users should be warned/educated about the need to ensure that `unicode` is used.

**Comment by rbarrois** [comment] 2016-09-04 10:33
I think that such a behavior would likely break in "pure" Django as well, where the expected behavior is:
* bytes -> str conversion at the external boundaries (SQL, HTTP, etc)
* str only in models and such

I'm closing this for now, since there hasn't been any report on that topic in the last couple of months.
Feel free to reopen the issue if you've been bitten by this ;)

**Closed by rbarrois** 2016-09-04 10:33 UTC
