### ISSUE TITLE
AttributeError: 'DatabaseWrapper' object has no attribute 'validation'

### ISSUE THREAD

**Issue by AdvancedUser** [django-ldapdb/django-ldapdb#92] opened 2016-07-20 06:46 UTC
We have some difficulties with the django-ldapdb module.
After attaching the module, the server doesn't always start and sometimes fall down with an error that is related to DatabaseWrapper

We followed examples as best we could, but didn't find the issue

[traceback.txt](https://github.com/django-ldapdb/django-ldapdb/files/372991/traceback.txt)

**Comment by dimtion** [comment] 2016-08-07 14:51
Hi @sonixblast,
So we ran in the same issue as you and this PR made the work : https://github.com/django-ldapdb/django-ldapdb/pull/90

**Comment by rbarrois** [comment] 2016-09-04 12:41
Hi,

I've been unable to reproduce this bug; would you have some example code around that I could use to isolate the bug?

**Comment by AdvancedUser** [comment] 2016-09-15 08:03
See attached a small project that may help you to isolate the bug.
[example_code.zip](https://github.com/django-ldapdb/django-ldapdb/files/474098/example_code.zip)

**Comment by pgrabo** [comment] 2016-10-13 11:12
Reproducible on django 1.9.1 and django-ldapdb==0.6.0. Traceback tail:
  File "*/.virtualenvs/dev/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 317, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
AttributeError: 'DatabaseWrapper' object has no attribute 'validation'

After applaying PR "Fixes AttributeError: 'DatabaseWrapper' object has no attribute 'validation' #100" manually, problem disappeared.

Could you please make new release with the fix included?

**Comment by rbarrois** [comment] 2016-10-24 13:00
Closed as fbefe52.

Reproduction was hard: we need a fully clean environment (no .pyc) to generate the error in ``./manage.py check``.

**Closed by rbarrois** 2016-10-24 13:00 UTC
Labels: bug, need-info
